### ISSUE TITLE
Question about action recognition on NTU

### ISSUE THREAD

**Issue by Fanstory** [dluvizon/deephar#26]
Hi,

Firstly, thank you for your project for introducing me a good idea to combine pose estimation and action recognition together.
I have a question regarding 'action recognition on NTU'.
I typed 'python3 exp/ntu/eval_ntu_ar_pe_merge.py' as you mentioned.
An error said "cannot import name'ntu_ar_dataconf' ". Where can I find it?

Thank you~

**Comment by hammb** [comment]
Change it to 'ntu_dataconf' in deephar\exp\ntu\eval_ntu_ar_pe_merge.py:

It should say:

`from deephar.config import ntu_dataconf`

In line 11 or something like that.

**Comment by preksha12** [comment]
> Hi,
> 
> Firstly, thank you for your project for introducing me a good idea to combine pose estimation and action recognition together.
> I have a question regarding 'action recognition on NTU'.
> I typed 'python3 exp/ntu/eval_ntu_ar_pe_merge.py' as you mentioned.
> An error said "cannot import name'ntu_ar_dataconf' ". Where can I find it?
> 
> Thank you~

How to setup this project as I have initially kept all videos in deephar/dataets/NTU/nturgb+d_rgb folder then when I tried to run python extract-resize-videos.py  it gave error

Expected 1 parameter, got ['extract-resize-videos.py']
Kindly tell me how to go about it from beginning for NTU dataset?

**Comment by hammb** [comment]
> I have initially kept all videos in deephar/dataets/NTU/nturgb+d_rgb folder

Saving the videos under this path is correct

The dataset is split in 17 parts. 
To extract the first part for example just execute the **extract-resize-videos.py** with **1** as command line argument.

`python extract-resize-videos.py 1`

**Comment by preksha12** [comment]
Hello, 
Thank you so much for your reply. I am now able to run that. Can you please tell me flow to implement the project (corresponding to 2020 paper) for NTU dataset. As I am not being clear with that.

**Comment by hammb** [comment]
As the weights for the 2020 model are not published, it is not so easy to replicate the results directly. The weights that have been published are for the 2018 results (under realeases in this repository). These weights are e.g. for the model from the script eval_ntu_ar_pe_merge.py.

So to reproduce the results of 2020 you would have to download all datasets, train the model with the script train_pose_baseline.py, save the weights and then train with train_ntu_spnet_benset.py.

Since the team from the Human3.6m dataset is not responding to my request to verify my access... I trained the model without it and had an accuracy of 82% on NTU. In a live test with my Kinect the results were not so good... but as I mentioned, I didn't have the Human3.6m dataset.

The model from 2018 worked better in my kinect v2 live test, because it is probably trained on human3.6m. so the pose estimation works better and based on that of course the action recognition. the model from 2020 without human3.6m does not recognize crossed arms and legs or e.g. a lifted leg for the "one foot hopping" class.

**Comment by preksha12** [comment]
Ok if I run all the files from scratch  (train_pose_baseline.py) for all datasets will I be able to get the exact results for NTU dataset?

**Comment by hammb** [comment]
Probably yes, but you need to be careful: Not with every number of frames per batch (num_frames) the batchloader works properly. For example, if I run the eval_ntu_multitask.py script with my model, at num_frames = 20, I have an accuracy of 98.7 percent. The number is only possible because most of the data could not be loaded, but unloaded data is somehow cathegorized by this script as correctly classified.

![grafik](https://user-images.githubusercontent.com/48390954/81173025-a6d88080-8f9f-11ea-8109-ae17a2153791.png)

**Comment by preksha12** [comment]
Ok will try then. Thank you.

**Comment by dluvizon** [comment]
Hi all,
Thank you for your interest in our work.
I have updated some thinks in the repo for the multitask model on MPII+PennAction. I'll try to upload the weights for NTU / Human3.6M in the next few days.

**Comment by sadiqamin** [comment]
Hi there, please explian the work flow of these codes as there is no insight how to work this code a simple image test.
