### ISSUE TITLE
Training hyperparameters for train_penn_multimodel.py 

### ISSUE THREAD

**Issue by edwardnguyen1705** [dluvizon/deephar#27]
Hi, thank you very much for releasing your excellent code. I just quit don't understand why you set the `initial_epoch = 7` here.

https://github.com/dluvizon/deephar/blob/6870fa32b11dcc99006c514679384ac70b1841a3/exp/pennaction/train_penn_multimodel.py#L150

As I understand, the PE is trained on MPII for 120 epochs, then weights related to PE are frozen and the AR is trained on Penn for 7 epochs, then the model weights are saved as `weights_mpii+penn_ar_007.hdf5`. 

Following that, full model is built, loaded weight, jointly trained start from `initial_epoch = 7`.
https://github.com/dluvizon/deephar/blob/6870fa32b11dcc99006c514679384ac70b1841a3/exp/pennaction/train_penn_multimodel.py#L84

Please confirm that I am wrong or right? Thanks.

**Comment by dluvizon** [comment]
Hi @edwardnguyen1705 ,
I'm sorry about the confusion here. This file was committed after a local modification to continue a training process.
If you notice, the weights loaded in l84 are referring to epoch 7:
https://github.com/dluvizon/deephar/blob/6870fa32b11dcc99006c514679384ac70b1841a3/exp/pennaction/train_penn_multimodel.py#L86
That's why the first stage action training is commented (with pose layers frozen)
https://github.com/dluvizon/deephar/blob/6870fa32b11dcc99006c514679384ac70b1841a3/exp/pennaction/train_penn_multimodel.py#L143
and the final training starts at epoch 7.

As reported in the paper, the first stage training is performed for 2 epochs on PA.

**Comment by edwardnguyen1705** [comment]
Hi @dluvizon,
Thanks for your explanation. I have conducted some experiments, and the results are consistent to those stated in your paper.
