### ISSUE TITLE
Questions regarding Pennaction folder

### ISSUE THREAD

**Issue by happyyqt** [dluvizon/deephar#31]
Hi Luvizon,

Thanks for your amazing work on pose estimation and action recognition field. It inspires me to dig further into this field. Here are some of my questions:
1. In the recently uploaded 'eval_penn_multitask.py', the input of the pose estimation model should be the size of (8,256,256,3) instead of (1,256,256,3) in the previous version. Why do you change that? Is that mean that the model will input 8 frames at a time? Since I am working on real-time implementation, the size is not very friendly to me now XD.
2. In the same folder exp/pennaction, does the file 'train_penn_multimodel.py' get the weights for the eval_penn_multitask.py? In the  'train_penn_multimodel.py', how do you get the pre-trained weights ''output/penn_multimodel_trial_15_only_mpii_pose_be215a3/weights_mpii+penn_ar_007.hdf5"? 

Thank you for your fantastic work and help.

**Comment by dluvizon** [comment]
Hi @happyyqt ,

1. It depends if the model also does action recognition or only pose estimation. In the first case, the input tensor has 5 dims `(batch_size, num_frames, height, width, channel)`. In the second case, `num_frames` does not exist. The `batch_size` you can change as you want, but the `num_frames` is fixed in the pre-trained models.

2. This was just because I stopped the training process at epoch 7 and then "resumed" it. You can ignore this file. However, as detailed in the paper, it is recommended to first train a model only with pose estimation for a better stability during the multitask training.
