### ISSUE TITLE
Informations about training

### ISSUE THREAD

**Issue by aleberello** [dluvizon/deephar#9]
Hi @dluvizon ,

First of all congrats for this work. I have some questions/clarification about this project.

1. If i right understand first you train the pose model, and after the action recognition model. How much time/epochs it need to obtain your result(or similar) training only action model on Pennaction, and how much for NTU?

2. Reading your paper seems that to work well the pose model must be train at least with some examples of action dataset that will be used for action recognition. Maybe better with an example, for action recognition on Pennaction, pose model it's trained with a part of this dataset before action model training, same for NTU, pose model it's trained with a part of NTU. Is this right observation? Is this very important for final performance on action recognition?

Thanks.

**Comment by dluvizon** [comment]
Hi @Aleberello ,

1. We first train the pose model, then we freeze it and train the action part, finally we fine tune the full model (pose+action). For PennAction, training is relatively fast (about one day) and for NTU it takes about 5 days, depending on your computational resources.

2. If I understood your statement correctly, yes. We use some samples from PennAction/NTU for first training the pose model because it allows the network to be adapted to these datasets. Although it is not required for the method, it brings small improvements in the final action recognition score.

**Comment by Peter654q** [comment]
Hi @dluvizon 
May I ask that which GPU you use in this experiments?
Thank you!

**Comment by dluvizon** [comment]
Tesla P100 for training, but it should be OK with GTX 1080 Ti too.
